import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { createTheme } from "@mui/material";
import { Toaster } from "react-hot-toast";
import ReduxProvider from "./components/ReduxProvider";

const montserrat = Montserrat({
  subsets: ["latin"],
});

declare module "@mui/material/styles" {
  interface Palette {
    gray: Palette["primary"];
    lightBlue: Palette["primary"];
    darkGreen: Palette["primary"];
    lightGreen: Palette["primary"];
  }

  interface PaletteOptions {
    gray?: PaletteOptions["primary"];
    lightBlue?: PaletteOptions["primary"];
    darkGreen?: PaletteOptions["primary"];
    lightGreen?: PaletteOptions["primary"];
  }
}

export const theme = createTheme({
  typography: {
    fontFamily: '"Montserrat", sans-serif',
    h1: {
      fontSize: "2.5rem",
      fontWeight: "700",
    },
    h2: {
      fontSize: "2rem",
      fontWeight: "700",
    },
    h3: {
      fontSize: "1.5rem",
      fontWeight: "700",
    },
    h4: {
      fontSize: "1.25rem",
      fontWeight: "400",
    },
    h5: {
      fontSize: "1rem",
      fontWeight: "400",
    },
    h6: {
      fontSize: "0.875rem",
      fontWeight: "400",
    },
    body1: {
      fontSize: "0.75rem",
      fontWeight: "400",
    },
    body2: {
      fontSize: "0.625rem",
      fontWeight: "400",
    },
  },
  palette: {
    common: {
      white: "#ffffff",
    },
    secondary: {
      main: "#252B42",
    },
    gray: {
      main: "#737373",
    },
    lightBlue: {
      main: "#23A6F0",
    },
    darkGreen: {
      main: "#23856D",
    },
    lightGreen: {
      main: "#2DC071",
    },
  },
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} antialiased`}>
        <Toaster />
        <ReduxProvider>
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
